import { test, expect } from '@playwright/test';
import { loginAs } from './helpers/auth';
import { createAndReopenAppointment } from './helpers/appointment';
import { format } from 'date-fns';

// NOTE: These tests require:
//   - Studio with at least one Location configured
//   - At least one completed appointment on a known date (generated by HP-SETTLE-2)
//   - Artist split rule configured (otherwise split_percent defaults to 0 — still valid)

const email = process.env.TEST_TESTER_EMAIL!;
const password = process.env.TEST_TESTER_PASSWORD!;

// We generate settlements for today's date in most tests.
// HP-SETTLE-2 first manually-completes a fresh appointment so the settlement
// has something to aggregate — avoids dependence on pre-existing data.
const TODAY = format(new Date(), 'yyyy-MM-dd');

test.describe('Daily Settlements', () => {
  test.beforeEach(async ({ page }) => {
    await loginAs(page, email, password);
    await page.goto('/settlements');
    await page.waitForLoadState('networkidle');
  });

  // ── Happy Paths ─────────────────────────────────────────────────────────────

  test('HP-SETTLE-1: /settlements page loads with heading and controls', async ({ page }) => {
    await expect(page.getByRole('heading', { name: /daily settlements/i })).toBeVisible({ timeout: 8000 });
    await expect(page.locator('input[type="date"]')).toBeVisible();
    await expect(page.getByRole('button', { name: /generate settlement|already settled/i })).toBeVisible();
  });

  test('HP-SETTLE-2: Generate settlement for today creates a locked record in history', async ({ page }) => {
    // First create and check out a fresh appointment so the settlement has data to aggregate.
    // We use the createAndReopenAppointment helper then perform a manual cash checkout.
    const apptDialog = await createAndReopenAppointment(page, 'E2E Settlement Client');

    const checkoutBtn = apptDialog.getByRole('button', { name: /check.?out/i });
    await expect(checkoutBtn).toBeVisible({ timeout: 5000 });
    await checkoutBtn.click();

    const checkoutDialog = page.getByRole('dialog').filter({ hasText: /check out appointment/i });
    await expect(checkoutDialog).toBeVisible({ timeout: 8000 });

    await checkoutDialog.locator('#charge_amount').fill('100.00');

    // Select Cash as payment method
    const payMethodTrigger = checkoutDialog.getByRole('combobox').last();
    await payMethodTrigger.click();
    await page.getByRole('option', { name: /cash/i }).click();

    await checkoutDialog.getByRole('button', { name: /manual checkout/i }).click();
    await expect(checkoutDialog).not.toBeVisible({ timeout: 10000 });
    await page.waitForLoadState('networkidle');

    // Now navigate to settlements and generate for today
    await page.goto('/settlements');
    await page.waitForLoadState('networkidle');

    // Ensure date is set to today
    const dateInput = page.locator('input[type="date"]');
    await dateInput.fill(TODAY);

    // If already settled for today, skip (idempotency — HP-SETTLE-4 covers the locked state)
    const generateBtn = page.getByRole('button', { name: /generate settlement/i });
    if (!await generateBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
      test.skip(true, 'Settlement already exists for today. Run HP-SETTLE-4 instead.');
      return;
    }

    await generateBtn.click();

    // Wait for the mutation to complete — button either changes to "Already Settled" or stays
    await expect(
      page.getByRole('button', { name: /already settled|generating/i })
        .or(page.getByRole('button', { name: /generate settlement/i }))
    ).toBeVisible({ timeout: 15000 });

    // Reload to see the history table update
    await page.waitForLoadState('networkidle');
    await page.reload();
    await page.waitForLoadState('networkidle');

    // The settlement history table should contain today's date
    await expect(page.getByText(TODAY)).toBeVisible({ timeout: 10000 });
    // Status should be "Locked"
    await expect(page.getByText(/locked/i).first()).toBeVisible({ timeout: 5000 });
  });

  test('HP-SETTLE-3: Settlement history table shows all financial columns', async ({ page }) => {
    // If no settlements exist yet, the empty state is acceptable
    const emptyState = page.getByText(/no settlements yet/i);
    const hasEmpty = await emptyState.isVisible({ timeout: 5000 }).catch(() => false);

    if (hasEmpty) {
      test.skip(true, 'No settlements in history — run HP-SETTLE-2 first to generate one.');
      return;
    }

    // Verify column headers are rendered
    await expect(page.getByRole('cell', { name: /date/i }).or(page.getByText(/^date$/i))).toBeVisible({ timeout: 5000 });
    await expect(page.getByText(/gross/i)).toBeVisible();
    await expect(page.getByText(/tax/i)).toBeVisible();
    await expect(page.getByText(/net/i)).toBeVisible();
    await expect(page.getByText(/pos/i)).toBeVisible();
    await expect(page.getByText(/online/i)).toBeVisible();
    await expect(page.getByText(/status/i)).toBeVisible();
  });

  test('HP-SETTLE-4: Settlement history shows dollar values in each row', async ({ page }) => {
    const hasEmpty = await page.getByText(/no settlements yet/i).isVisible({ timeout: 5000 }).catch(() => false);
    if (hasEmpty) {
      test.skip(true, 'No settlements — run HP-SETTLE-2 first.');
      return;
    }

    // Each settlement row should have at least one dollar amount rendered (e.g. "$100.00")
    await expect(page.getByText(/\$\d+\.\d{2}/).first()).toBeVisible({ timeout: 8000 });
  });

  test('HP-SETTLE-5: Location filter narrows settlement history to selected location', async ({ page }) => {
    const hasEmpty = await page.getByText(/no settlements yet/i).isVisible({ timeout: 5000 }).catch(() => false);
    if (hasEmpty) {
      test.skip(true, 'No settlements yet — run HP-SETTLE-2 first.');
      return;
    }

    // Open the location filter
    const locationTrigger = page.getByRole('combobox').last();
    if (!await locationTrigger.isVisible({ timeout: 3000 }).catch(() => false)) {
      test.skip(true, 'Location filter combobox not found.');
      return;
    }

    await locationTrigger.click();
    const firstOption = page.getByRole('option').first();
    if (!await firstOption.isVisible({ timeout: 5000 }).catch(() => false)) {
      await page.keyboard.press('Escape');
      test.skip(true, 'No location options in filter.');
      return;
    }

    const locationName = await firstOption.textContent();
    await firstOption.click();
    await page.waitForTimeout(500);

    // Page should still load without crashing
    await expect(page.locator('body')).not.toBeEmpty();
    // History table (or empty state) should update
    const hasRows = await page.getByText(/\$\d+\.\d{2}/).first().isVisible({ timeout: 5000 }).catch(() => false);
    const hasNoRows = await page.getByText(/no settlements yet/i).isVisible({ timeout: 3000 }).catch(() => false);
    expect(hasRows || hasNoRows).toBe(true);
  });

  test('HP-SETTLE-6: Settlement line items — artist split reflected in net amounts', async ({ page }) => {
    // This is a data integrity test — validates that the settlement mutation correctly
    // calculated artist_share + shop_share using the split rule.
    // We verify indirectly: if a settlement was generated for a completed appointment
    // belonging to an artist with a 60% split rule, the settlement gross should be
    // non-zero and the net = gross - tax - discounts.
    const hasEmpty = await page.getByText(/no settlements yet/i).isVisible({ timeout: 5000 }).catch(() => false);
    if (hasEmpty) {
      test.skip(true, 'No settlements — run HP-SETTLE-2 first.');
      return;
    }

    // Find the row for today (if it exists)
    const todayRow = page.locator('tr').filter({ hasText: TODAY }).first();
    if (!await todayRow.isVisible({ timeout: 3000 }).catch(() => false)) {
      test.skip(true, 'No settlement row for today — run HP-SETTLE-2 first.');
      return;
    }

    // Extract gross and net — both should be parseable dollar amounts
    const cells = todayRow.locator('td');
    const grossCell = cells.nth(2);
    const netCell = cells.nth(5);

    const grossText = await grossCell.textContent();
    const netText = await netCell.textContent();

    const gross = parseFloat(grossText?.replace('$', '') || '0');
    const net = parseFloat(netText?.replace('$', '') || '0');

    // Net must be <= gross (discounts/tax only ever reduce it)
    expect(net).toBeLessThanOrEqual(gross);
    expect(gross).toBeGreaterThanOrEqual(0);
  });

  // ── Non-Happy Paths ─────────────────────────────────────────────────────────

  test('NHP-SETTLE-7: "Already Settled" button disabled when settlement exists for selected date', async ({ page }) => {
    const hasEmpty = await page.getByText(/no settlements yet/i).isVisible({ timeout: 5000 }).catch(() => false);
    if (hasEmpty) {
      test.skip(true, 'No settlements exist yet — run HP-SETTLE-2 to create one, then re-run.');
      return;
    }

    // Find any settled date in the history and set the date filter to it
    const firstDateCell = page.locator('tbody tr td').first();
    if (!await firstDateCell.isVisible({ timeout: 5000 }).catch(() => false)) {
      test.skip(true, 'No settlement rows in history table.');
      return;
    }

    const settledDate = await firstDateCell.textContent();
    if (!settledDate) {
      test.skip(true, 'Could not read settlement date from history.');
      return;
    }

    // Set the date input to the already-settled date
    await page.locator('input[type="date"]').fill(settledDate.trim());
    await page.waitForTimeout(500);

    // Generate button should be disabled and labelled "Already Settled"
    const alreadySettledBtn = page.getByRole('button', { name: /already settled/i });
    await expect(alreadySettledBtn).toBeVisible({ timeout: 5000 });
    await expect(alreadySettledBtn).toBeDisabled();
  });

  test('NHP-SETTLE-8: Non-admin sees access restricted message', async ({ page }) => {
    // This test validates the access guard renders properly.
    // Since our test user IS admin, we verify the page is accessible (guard NOT shown).
    // To test the restricted path you would need a Front_Desk test account.
    await expect(page.getByRole('heading', { name: /daily settlements/i })).toBeVisible({ timeout: 8000 });
    // If the guard is incorrectly applied, we would see "Access Restricted" even for admin
    await expect(page.getByText(/only owners and admins/i)).not.toBeVisible();
  });

  test('NHP-SETTLE-9: Generating settlement with no completed appointments for date creates no record', async ({ page }) => {
    // Pick a date far in the future where no appointments can be completed yet
    const futureDate = '2099-12-31';
    await page.locator('input[type="date"]').fill(futureDate);
    await page.waitForTimeout(400);

    const generateBtn = page.getByRole('button', { name: /generate settlement/i });
    if (!await generateBtn.isEnabled({ timeout: 3000 }).catch(() => false)) {
      // Already settled for that date somehow — skip
      test.skip(true, 'Settlement already exists for 2099-12-31 — unexpected.');
      return;
    }

    await generateBtn.click();
    await page.waitForTimeout(2000);
    await page.waitForLoadState('networkidle');

    // No row for 2099-12-31 should appear in the history table
    // (the mutation skips locations with 0 completed appointments)
    const futureRow = page.locator('tr').filter({ hasText: '2099-12-31' });
    await expect(futureRow).not.toBeVisible({ timeout: 5000 });
  });
});
